CREATE DATABASE tisea;

USE tisea;

CREATE TABLE `tisea_users` (
	`username` VARCHAR(20) NOT NULL,
	`email` VARCHAR(64) NOT NULL,
	`password_hash` TEXT NOT NULL,
	`nickname` VARCHAR(20) DEFAULT "",
	`bio` VARCHAR(50) DEFAULT "",
	`id` INT unsigned NOT NULL AUTO_INCREMENT,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`group_id` INT unsigned NOT NULL DEFAULT 0,
	`level` INT unsigned NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
);

CREATE TABLE `tisea_dynamics` (
	`id` INT unsigned NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(20) NOT NULL,
	`content` TEXT NOT NULL,
	`author` VARCHAR(20) NOT NULL,
	`hidden` BOOLEAN NOT NULL DEFAULT 0,
	`categories` JSON DEFAULT NULL,
	`tags` JSON DEFAULT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);